"""Add ~30 new diverse, substantive alerts to templates.json to reach ~70 total."""
import json, pathlib

path = pathlib.Path(__file__).parent.parent / "ipaws_research/resources/templates.json"
data = json.loads(path.read_text(encoding="utf-8"))

NEW_WEATHER = [
    "Winter Storm Warning issued January 7 at 4:00AM PST until January 8 at 12:00PM PST by NWS Sacramento CA\n\nThe National Weather Service in Sacramento has issued a Winter Storm Warning for...\nSierra Nevada Mountains above 4000 feet in northern California...\n\n* Until noon PST Saturday.\n\n* At 400 AM PST, a powerful storm system was approaching the region bringing heavy snow to elevations above 4000 feet, with ice accumulations possible at lower elevations along the I-80 and Highway 50 corridors.\n\nHAZARD...Heavy snow and ice. Total snow accumulations of 2 to 4 feet above 7000 feet. Ice accumulations of up to one tenth of an inch at 4000 to 5000 feet.\n\nSOURCE...NWS Sacramento.\n\nIMPACT...Travel will be very difficult to impossible. The hazardous conditions will impact the morning and evening commutes. Hypothermia and frostbite risk to those without adequate shelter.\n\n* Locations impacted include...\nTahoe City, South Lake Tahoe, Truckee, Donner Summit, Echo Summit, and the I-80 corridor through the mountains.",

    "Excessive Heat Warning issued July 12 at 6:00AM PDT until July 14 at 9:00PM PDT by NWS Hanford CA\n\nThe National Weather Service in Hanford has issued an Excessive Heat Warning for...\nSan Joaquin Valley in central California...\nSouthern Sacramento Valley...\n\n* From 6 AM PDT Saturday through 9 PM PDT Monday.\n\n* Maximum temperatures 110 to 115 degrees. Minimum temperatures overnight 80 to 85 degrees.\n\nHAZARD...Dangerously hot conditions. Heat index values up to 115 degrees.\n\nSOURCE...National Weather Service.\n\nIMPACT...Extreme heat will significantly increase the potential for heat related illnesses, particularly for those working or participating in outdoor activities. Elderly, young children, pets, and those in poor health are at heightened risk.\n\nDrink plenty of fluids, stay in an air-conditioned room, stay out of the sun, and check up on relatives and neighbors. Never leave young children or pets unattended in vehicles. Cooling centers are available. Call 211 for locations.\n\n* Locations impacted include...\nFresno, Bakersfield, Visalia, Tulare, Stockton, Modesto, Clovis, Hanford, Porterville, and Lemoore.",

    "Severe Thunderstorm Warning issued April 18 at 2:34PM PDT until April 18 at 3:15PM PDT by NWS Sacramento CA\n\nThe National Weather Service in Sacramento has issued a Severe Thunderstorm Warning for...\nNortheastern Sacramento County in north central California...\nNorthern San Joaquin County in north central California...\n\n* Until 315 PM PDT.\n\n* At 234 PM PDT, a severe thunderstorm was located 8 miles north of Folsom, moving east at 45 mph.\n\nHAZARD...60 mph wind gusts and quarter size hail.\n\nSOURCE...Radar indicated.\n\nIMPACT...Hail damage to vehicles is expected. Expect wind damage to roofs, siding, and trees.\n\n* Locations impacted include...\nFolsom, Rancho Cordova, Elk Grove, Auburn, Rocklin, Roseville, Loomis, Penryn, Lincoln, Granite Bay, Orangevale and Gold River.",

    "High Wind Warning issued October 4 at 11:00PM PDT until October 5 at 5:00PM PDT by NWS Los Angeles/Oxnard CA\n\nThe National Weather Service in Los Angeles/Oxnard has issued a High Wind Warning for...\nSanta Ana Mountains and Foothills in southern California...\nSan Gabriel Valley in southern California...\n\n* Until 5 PM PDT Sunday.\n\n* Southwest winds of 35 to 50 mph with gusts up to 80 mph are expected. Locally gusts up to 90 mph are possible in the higher terrain and canyon areas.\n\nHAZARD...Dangerously high winds with gusts up to 90 mph.\n\nSOURCE...National Weather Service.\n\nIMPACT...Damaging winds will blow down large objects such as trees and power lines. Widespread power outages are expected. Travel will be difficult, especially for high profile vehicles. Flying debris will result in injuries. Extreme fire behavior possible.\n\n* Locations impacted include...\nPasadena, Arcadia, Monrovia, Glendora, San Dimas, La Verne, Claremont, Upland, and Rancho Cucamonga.",

    "Dense Fog Advisory issued November 28 at 11:00PM PST until November 29 at 11:00AM PST by NWS Hanford CA\n\nThe National Weather Service in Hanford has issued a Dense Fog Advisory for...\nSan Joaquin Valley including Fresno, Kings, Tulare, and Madera counties in central California...\n\n* Until 11 AM PST Thursday.\n\n* Visibility will frequently drop to a quarter mile or less in dense fog during the overnight hours through the morning commute.\n\nHAZARD...Dense fog.\n\nSOURCE...National Weather Service.\n\nIMPACT...Dangerous driving conditions expected. Major highway delays possible on Highway 99, Interstate 5, and Highway 65.\n\nIf driving, slow down. Use low-beam headlights. Increase your following distance. Do not use high-beam headlights in fog. Pull to the side of the road and turn on hazard lights if visibility drops to zero.\n\n* Locations impacted include...\nFresno, Bakersfield, Visalia, Tulare, Clovis, Hanford, Porterville, Reedley, Selma, Fowler, Sanger, and Dinuba.",

    "Dust Storm Warning issued August 20 at 2:15PM PDT until August 20 at 5:00PM PDT by NWS Las Vegas NV\n\nThe National Weather Service in Las Vegas has issued a Dust Storm Warning for...\nSoutheastern San Bernardino County in southern California...\n\n* Until 500 PM PDT.\n\n* At 215 PM PDT, a large wall of dust was observed in the desert near Barstow moving westward at 35 mph along the I-15 and I-40 corridors. Visibility will drop to near zero.\n\nHAZARD...Blinding dust.\n\nSOURCE...Spotter reports.\n\nIMPACT...Zero visibility will create hazardous driving conditions.\n\nIf you encounter dust on a roadway, PULL ASIDE - STAY ALIVE: Pull completely off the pavement, turn off your lights, take your foot off the brakes, and wait for the storm to pass. Do NOT stop in a travel lane.\n\n* Locations impacted include...\nBarstow, Twentynine Palms, Needles, Blythe, Baker, Victorville, and Ludlow.",

    "Freeze Warning issued January 12 at 10:00PM PST until January 13 at 9:00AM PST by NWS Los Angeles/Oxnard CA\n\nThe National Weather Service in Los Angeles/Oxnard has issued a Freeze Warning for...\nInterior portions of Los Angeles County in southern California...\nVentura County interior valleys...\n\n* From 10 PM PST Tuesday to 9 AM PST Wednesday.\n\n* Temperatures as low as 26 to 30 degrees are expected.\n\nHAZARD...Hard freeze.\n\nSOURCE...National Weather Service.\n\nIMPACT...A hard freeze will kill crops and other sensitive vegetation. Pipes may freeze and burst.\n\nTo prepare: Bring tender plants inside. Allow faucets to drip slightly. Open cabinet doors beneath sinks. Wrap exposed pipes. Keep your home heated overnight. Check on elderly family members or neighbors.\n\n* Locations impacted include...\nSanta Clarita, Saugus, Valencia, Canyon Country, Lancaster, Palmdale, Woodland Hills, Chatsworth, Northridge, Pacoima, San Fernando and Sylmar.",

    "Rip Current Statement issued June 10 at 6:00AM PDT by NWS Los Angeles/Oxnard CA\n\nThe National Weather Service in Los Angeles/Oxnard has issued a Rip Current Statement for...\nLos Angeles County Beaches in southern California...\nVentura County Beaches in southern California...\n\n* Through Friday evening.\n\n* A combination of elevated northwest swell, south swell, and above-normal surf of 4 to 7 feet will produce dangerous rip currents at area beaches through Friday evening.\n\nHAZARD...Dangerous rip currents.\n\nSOURCE...National Weather Service.\n\nIMPACT...Rip currents are powerful channels of water flowing quickly away from shore. They can sweep even the strongest swimmer out to sea.\n\nIF CAUGHT IN A RIP CURRENT: Do not fight the current. Swim parallel to shore until free of the current, then swim to shore. If you cannot escape, float or tread water and signal for help.\n\nSwim near a lifeguard. Obey all flag and sign warnings. Do not enter the water if rip currents are possible.\n\n* Locations impacted include...\nSanta Monica, Malibu, Zuma Beach, Ventura, Oxnard, Point Mugu, and Camarillo.",
]

NEW_EVACUATION = [
    "MANDATORY EVACUATION ORDER - DAM FAILURE THREAT\nBUTTE COUNTY OFFICE OF EMERGENCY SERVICES has issued a MANDATORY EVACUATION ORDER for all residents in Oroville Low Zones A through E due to the imminent threat of Oroville Dam spillway failure.\n\nResidents in the affected zones MUST leave immediately. Do not wait. This is not a drill.\n\nEvacuation routes: Highway 70 North to Quincy, or Highway 162 West toward Chico. Avoid Highway 99 South which is currently congested.\n\nEvacuation Centers have been established at:\n- Silver Dollar Fairgrounds, Chico (2357 Fair St)\n- Gridley Community Center (655 Kentucky St)\n\nBring medications, important documents, and enough clothing and supplies for 72 hours. Take pets if possible. Do not return until notified by official sources.\n\nFor information: Butte County OES 530-538-7920 or visit ReadyButte.com",

    "TSUNAMI WARNING - CALIFORNIA COAST\nNATIONAL TSUNAMI WARNING CENTER has issued a Tsunami Warning for the California coast from the Oregon border to the Mexican border.\n\nA magnitude 9.1 earthquake occurred at 4:47 AM PST off the coast of Northern California. Dangerous tsunami waves are expected to begin arriving at coastal California locations within 15 to 45 minutes of this message.\n\nACTION REQUIRED: MOVE INLAND OR TO HIGH GROUND NOW. Leave low-lying coastal areas immediately. Move to at least 100 feet above sea level or 1 mile inland.\n\nTsunami waves may be 10 to 30 feet high or higher. They will arrive as multiple waves over many hours. The first wave may not be the largest. Do not return to the coast until an ALL CLEAR is issued by official sources.\n\nThis warning affects: All coastal areas, harbors, marinas, beaches, and low-lying areas adjacent to the coast.\n\nFor information: NOAA National Tsunami Warning Center. Follow instructions from local emergency management.",

    "HAZARDOUS MATERIALS INCIDENT - SHELTER IN PLACE\nVENTURA COUNTY FIRE DEPARTMENT and VENTURA COUNTY OES have issued a SHELTER IN PLACE ORDER for residents within a 1-mile radius of 4700 Market Street, Oxnard, California due to a major chlorine gas leak at a water treatment facility.\n\nIMMEDIATELY: If you are indoors, remain indoors. Close all windows, doors, and fireplace dampers. Turn off all fans, air conditioning, and heating systems. If you must go outside to reach a safer location, cover your nose and mouth with a damp cloth and move quickly upwind to higher ground.\n\nSymptoms of chlorine exposure: burning eyes, nose, and throat; coughing; difficulty breathing; nausea. If you experience these symptoms, call 911 immediately.\n\nResidents within the 1-mile radius should NOT attempt to drive out as traffic could interfere with emergency response vehicles.\n\nUpdates will be provided via this channel every 30 minutes. For life-threatening emergencies call 911.",

    "EVACUATION ORDER - FAST-MOVING WILDFIRE\nCALIFORNIA DEPARTMENT OF FORESTRY AND FIRE PROTECTION (CAL FIRE) and RIVERSIDE COUNTY SHERIFF have issued an EVACUATION ORDER for the following zones due to a rapidly spreading wildfire:\n\nZones: RIV-AGUA-001, RIV-AGUA-002, RIV-AGUA-003, RIV-AGUA-004\nAreas: Aguanga, Oak Grove, Hamilton Ranch Road corridor, and areas north of Highway 79.\n\nFIRE CONDITIONS: The fire is moving at extreme rate of spread driven by 40 mph wind gusts. Structures in the ordered zones are immediately threatened.\n\nLEAVE NOW. Do not attempt to return to pack belongings. Take the following routes:\n- South: Highway 79 to Temecula\n- West: Sage Road to Interstate 215\n\nDo NOT use Cahuilla Road - it is currently cut off by fire.\n\nEvacuation Center: Southwest Community College, 900 Otay Lakes Road, Temecula.\n\nPets and livestock: Large animal evacuation at Rancho California Sports Park.\n\nCAL FIRE Incident: 951-940-6900 | ReadyRiverside.org",

    "EVACUATION WARNING - GAS MAIN RUPTURE\nLOS ANGELES FIRE DEPARTMENT has issued an EVACUATION WARNING for all residents within 2 blocks of the intersection of Sunset Boulevard and Vine Street, Hollywood, due to a major natural gas main rupture with fire risk.\n\nA SoCalGas crew is on scene working to isolate the rupture. The area is considered unsafe due to explosive gas concentrations.\n\nResidents and businesses in the affected area should evacuate immediately to: Hollywood Recreation Center, 1122 Cole Ave.\n\nDo not operate any electrical switches, use phones, or start vehicles near the rupture site. Do not smoke or use open flame.\n\nFor emergencies: 911 | LAFD Information: lafd.org or @LAFD on social media.",
]

NEW_PUBLIC_SAFETY = [
    "LAW ENFORCEMENT ADVISORY - ARMED AND DANGEROUS SUSPECT\nLOS ANGELES SHERIFF'S DEPARTMENT has issued a Law Enforcement Advisory for residents in the North Hills community of Los Angeles.\n\nDeputies are currently searching for an armed and dangerous suspect following a shooting incident near Nordhoff Street and Balboa Boulevard. The suspect is a Hispanic male, approximately 25-30 years old, 5 feet 9 inches tall, wearing a blue hoodie and gray jeans, last seen on foot heading north on Balboa Boulevard.\n\nRESIDENTS ARE ADVISED: Do not approach this individual. If you see the suspect, call 911 immediately. Lock your doors and remain indoors until deputies advise the area is clear.\n\nSchools placed on secure campus: North Hills Elementary, Elliot Arts Magnet, and Patrick Henry Middle School.\n\nFor non-emergency inquiries: (213) 229-1700.",

    "BOIL WATER ADVISORY - WATER SYSTEM FAILURE\nCITY OF SAN BERNARDINO MUNICIPAL WATER DEPARTMENT has issued a BOIL WATER ADVISORY for all customers in Service Zones 3, 7, and 12, affecting approximately 45,000 residents.\n\nREASON: A water main break caused a loss of pressure, which may have allowed contaminants to enter the water supply.\n\nACTION REQUIRED: All tap water used for drinking, cooking, making ice, brushing teeth, and washing dishes must be BOILED before use.\n\nHow to boil water safely:\n1. Bring water to a full rolling boil for at least 1 minute\n2. Allow to cool and store in a clean, covered container\n3. Bottled water is safe to use without boiling\n\nBottled water distribution sites:\n- San Bernardino City Hall, 300 N D St (9 AM - 6 PM)\n- Rudy C. Hernandez Community Center, 222 N Lugo Ave (9 AM - 5 PM)\n\nThis advisory will remain in effect until further notice. Testing results expected within 48 hours.\n\nFor information: 909-384-5143 or sbcity.org",

    "CIVIL EMERGENCY MESSAGE - MAJOR POWER OUTAGE\nPACIFIC GAS AND ELECTRIC COMPANY and CALIFORNIA ISO have issued an emergency notice of widespread power outages affecting Northern and Central California due to a major transmission grid failure.\n\nApproximately 2.1 million customers are without power in Sacramento, San Joaquin, Stanislaus, Merced, Fresno, Tulare, Kings, and Madera counties.\n\nEstimated restoration: 24 to 72 hours. Restoration will occur in stages beginning with critical infrastructure.\n\nPRECAUTIONS:\n- Do not use candles unattended - use flashlights\n- Never use generators, gas ranges, or barbecues indoors\n- Keep refrigerator and freezer doors closed to preserve food\n- Conserve phone battery charge\n- Check on elderly neighbors and family members\n\nEmergency shelters with power: Contact 211 for locations.\n\nFor outage status: pge.com/outages or call 1-800-743-5000.",

    "CIVIL EMERGENCY - SEISMIC AFTERSHOCK WARNING\nCALIFORNIA OFFICE OF EMERGENCY SERVICES and the USGS have issued a Seismic Aftershock Warning for the Greater Los Angeles area following a 6.4 magnitude earthquake centered 8 miles southwest of Compton.\n\nAt least 12 multi-story buildings in the affected area have sustained moderate to severe structural damage. Several gas line breaks have been reported in Watts, Compton, and South Los Angeles.\n\nIMPORTANT SAFETY INFORMATION:\n- AFTERSHOCKS ARE EXPECTED. A 5.0 or greater magnitude aftershock has a high probability within the next 24 hours.\n- If you are in a damaged building, evacuate immediately\n- Turn off gas at the meter if you smell gas or suspect a leak\n- Do not use candles, lighters, or matches until gas leaks are ruled out\n- Do not use elevators\n- Check for injured neighbors and call 911 for life-threatening emergencies\n\nEmergency Shelter: Inglewood Forum, 3900 W Manchester Blvd\n\nFor information: LA County OES 213-978-0700 | lacounty.gov/emergency",

    "RAILROAD INCIDENT - EVACUATION ORDER\nUNION PACIFIC RAILROAD and PLACER COUNTY OES have declared an Environmental Emergency following the derailment of a freight train carrying anhydrous ammonia near Colfax, California.\n\nTwo tank cars containing anhydrous ammonia have breached, releasing toxic gas. Wind is carrying the plume in a southwesterly direction.\n\nEVACUATION ORDER: All residents within 1 mile south and 0.5 miles west of Colfax must evacuate immediately.\n\nEvacuation route: Interstate 80 East toward Donner Summit, or Highway 174 North toward Grass Valley. Do not travel southwest.\n\nSYMPTOMS of ammonia exposure: Burning sensation in eyes, nose, and throat; coughing; difficulty breathing; watery eyes. Seek immediate medical attention if you experience symptoms.\n\nEvacuation Center: Dewitt Community Center, 1350 Bella Vista Rd, Auburn.\n\nFor information: Placer County OES 530-886-5170 | ReadyPlacer.com",
]

NEW_HEALTH = [
    "PUBLIC HEALTH EMERGENCY - CONFIRMED OUTBREAK\nLOS ANGELES COUNTY DEPARTMENT OF PUBLIC HEALTH has declared a Public Health Emergency in response to a confirmed outbreak of Shiga toxin-producing E. coli O157:H7 linked to romaine lettuce sold at multiple retail locations in Los Angeles County.\n\nAs of this notice, 47 confirmed cases and 12 hospitalizations have been reported. Symptoms include severe stomach cramps, diarrhea (often bloody), and vomiting, typically appearing 3 to 4 days after consuming the contaminated product.\n\nIMPACT: The affected product is Romaine lettuce sold in bags branded 'Fresh Farms' or 'Valley Select' with sell-by dates between March 10 and March 25, 2026.\n\nACTION REQUIRED:\n- If you have this product, do not eat it - discard it immediately\n- Wash hands, counters, and utensils thoroughly\n- If you develop symptoms, contact your healthcare provider\n\nFree testing is available at County public health clinics. Call 1-800-427-8700 for the nearest location.\n\nFor more information: publichealth.lacounty.gov",

    "PUBLIC HEALTH ADVISORY - EXTREME HEAT AND AIR QUALITY EMERGENCY\nSAN JOAQUIN VALLEY AIR POLLUTION CONTROL DISTRICT and FRESNO COUNTY PUBLIC HEALTH have issued a combined Extreme Heat and Air Quality Emergency for Fresno County.\n\nHEAT CONDITIONS: Temperatures of 112 to 117 degrees Fahrenheit are expected through Saturday. These are record or near-record temperatures.\n\nAIR QUALITY: Combined with widespread wildfire smoke, the Air Quality Index (AQI) is 185 (Unhealthy). Fine particle pollution is at dangerous levels.\n\nHEALTH IMPACTS: Prolonged heat and poor air quality together substantially increase the risk of heat stroke, cardiovascular events, and respiratory emergencies, especially for elderly, young children, outdoor workers, and those with respiratory or heart conditions.\n\nPROTECT YOURSELF:\n- Stay indoors in air conditioning as much as possible\n- If you do not have AC, go to a cooling center immediately\n- Drink water frequently - at least 8 glasses per day\n- Wear an N95 mask if you must go outside\n- Check on elderly and vulnerable neighbors\n\nCooling Centers: Visit 211fresno.org or call 2-1-1 for the nearest location.",

    "PUBLIC HEALTH ALERT - WILDFIRE SMOKE AIR QUALITY EMERGENCY\nBAY AREA AIR QUALITY MANAGEMENT DISTRICT has issued a Spare the Air Alert and Smoke Health Advisory for the nine-county Bay Area.\n\nThe Mendocino Fire, now 145,000 acres and 15% contained, is producing dense smoke that is drifting into the Bay Area. Air quality is currently measured at UNHEALTHY TO VERY UNHEALTHY (AQI 175-220) across the region.\n\nResidents with heart or lung conditions, elderly, children, and pregnant women face the highest risk.\n\nWHAT TO DO:\n- Remain indoors and keep windows and doors closed\n- Use air conditioning on recirculate mode - do NOT use fresh air mode\n- Use a HEPA air purifier if available\n- Wear an N95 or KN95 mask if you must go outside - cloth masks do NOT protect against smoke particles\n- Avoid strenuous outdoor activity\n\nSPARE THE AIR: Do not use wood-burning fireplaces or stoves. No exceptions.\n\nFor air quality levels: airnow.gov or baaqmd.gov",

    "EMERGENCY HEALTH ADVISORY - MENINGITIS OUTBREAK\nSANTA CLARA COUNTY PUBLIC HEALTH DEPARTMENT has issued an Emergency Health Advisory following four confirmed cases of bacterial meningitis among students at San Jose State University.\n\nCases were identified over a five-day period. All four students have been hospitalized; one remains in critical condition.\n\nWARNING SIGNS: Sudden severe headache, high fever, stiff neck, sensitivity to light, confusion, vomiting, and small red or purple spots on skin.\n\nIF YOU EXPERIENCE ANY SYMPTOMS: Call 911 or go to the nearest emergency room IMMEDIATELY. Do not wait - bacterial meningitis can be fatal within 24 to 48 hours without treatment.\n\nVACCINATION: Free meningococcal vaccines are being offered to all current SJSU students and close contacts at SJSU Student Wellness Center, Thursday through Saturday, 8 AM to 6 PM.\n\nFor information: sccgov.org/publichealth or call (408) 885-4214",

    "PUBLIC HEALTH NOTICE - WATER SAFETY ADVISORY FOR PRIVATE WELL OWNERS\nCARBON COUNTY DEPARTMENT OF PUBLIC HEALTH has issued a Water Safety Notice for private well owners in the Green River Formation area due to elevated arsenic levels detected in groundwater testing.\n\nBACKGROUND: Recent sampling of 38 private wells found arsenic levels above the EPA maximum contaminant level of 10 micrograms per liter. The highest level detected was 78 micrograms per liter.\n\nHEALTH RISK: Long-term exposure above the EPA standard is associated with increased risk of skin, bladder, and lung cancers, as well as cardiovascular effects.\n\nACTION REQUIRED if you have a private well:\n- Do NOT drink, cook with, or brush teeth with well water until tested\n- Use bottled water or water from a tested safe source\n- Contact Carbon County Public Health for FREE well testing: 307-328-0910\n\nThis notice does not affect municipal water supplies, which are regularly tested and treated.\n\nFor more information: carbon.wyo.gov/publichealth",
]

# Append to existing categories
data["weather"].extend(NEW_WEATHER)
data["evacuation"].extend(NEW_EVACUATION)
data["public_safety"].extend(NEW_PUBLIC_SAFETY)
data["health"].extend(NEW_HEALTH)

total = sum(len(v) for v in data.values())
for k, v in data.items():
    print(f"  {k:15s}: {len(v):2d} entries")
print(f"  {'TOTAL':15s}: {total}")

path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
print("templates.json expanded.")
